version: "3.8"
services:
  mongoman:
    image: mongo
    container_name: hardhome-mongo-prod
    restart: always
    networks:
      - hardhome-network-prod
    volumes:
      - "./mongodata:/data/db"  

  backend-service:
    environment:
      MONGO_CONNECTION_STRING: ${MONGO_CONNECTION_STRING}
    image: 121487958432.dkr.ecr.us-east-1.amazonaws.com/hardhome-backend-service-image-prod:latest
    container_name: hardhome-backend-service-prod
    restart: on-failure
    ports:
      - 3090:3090
    networks:
      - hardhome-network-prod
    depends_on:
      - mongoman

  api-service:
    image: 121487958432.dkr.ecr.us-east-1.amazonaws.com/hardhome-api-service-image-prod:latest
    container_name: hardhome-api-service-prod
    restart: on-failure
    ports:
      - 3091:3091
    networks:
      - hardhome-network-prod
    command: npm start  

  frontend-service:
    image: 121487958432.dkr.ecr.us-east-1.amazonaws.com/hardhome-frontend-service-image-prod:latest
    container_name: hardhome-frontend-service-prod
    volumes:
      - "./envfile:/usr/share/nginx/html/env/envfile"
    ports:
      - "12090:80"
    restart: on-failure    

networks:
  hardhome-network-prod:
    name: hardhome-docker-network-prod
    driver: bridge